apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gctd44cqt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gctd44cqt-go 
  name: gctd44cqt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gctd44cqt-go 
